setx STORMPATH_CLIENT_APIKEY_ID "7H3W588H1OD6ZBHJ7FXFM4DM9"
setx STORMPATH_CLIENT_APIKEY_SECRET "Pc3Rq+MF3hPlCNGEaB2AZ46BXSWbDv84AFqXEbCwWCI"
setx STORMPATH_APPLICATION_HREF "https://api.stormpath.com/v1/applications/1zY4facmsIrTCa3icVZjrf"
setx STORMPATH_NAME "Stormpath"